
package com.rsi.kino.client.serve_kino;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DocumentException", targetNamespace = "http://serve_kino/")
public class DocumentException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DocumentException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DocumentException_Exception(String message, DocumentException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DocumentException_Exception(String message, DocumentException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: serve_kino.DocumentException
     */
    public DocumentException getFaultInfo() {
        return faultInfo;
    }

}
