
package com.rsi.kino.client.serve_kino;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KinoService", targetNamespace = "http://serve_kino/", wsdlLocation = "http://localhost:8081/ws/serve_kino?wsdl")
public class KinoService
    extends Service
{

    private final static URL KINOSERVICE_WSDL_LOCATION;
    private final static WebServiceException KINOSERVICE_EXCEPTION;
    private final static QName KINOSERVICE_QNAME = new QName("http://serve_kino/", "KinoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/serve_kino?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KINOSERVICE_WSDL_LOCATION = url;
        KINOSERVICE_EXCEPTION = e;
    }

    public KinoService() {
        super(__getWsdlLocation(), KINOSERVICE_QNAME);
    }

    public KinoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KINOSERVICE_QNAME, features);
    }

    public KinoService(URL wsdlLocation) {
        super(wsdlLocation, KINOSERVICE_QNAME);
    }

    public KinoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KINOSERVICE_QNAME, features);
    }

    public KinoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KinoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Kino
     */
    @WebEndpoint(name = "KinoPort")
    public Kino getKinoPort() {
        return super.getPort(new QName("http://serve_kino/", "KinoPort"), Kino.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Kino
     */
    @WebEndpoint(name = "KinoPort")
    public Kino getKinoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serve_kino/", "KinoPort"), Kino.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KINOSERVICE_EXCEPTION!= null) {
            throw KINOSERVICE_EXCEPTION;
        }
        return KINOSERVICE_WSDL_LOCATION;
    }

}
