
package com.rsi.kino.client.serve_kino;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ObjectNotFoundException", targetNamespace = "http://serve_kino/")
public class ObjectNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ObjectNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ObjectNotFoundException_Exception(String message, ObjectNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ObjectNotFoundException_Exception(String message, ObjectNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: serve_kino.ObjectNotFoundException
     */
    public ObjectNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
